version: "3.8"

services:
  db:
    image: mysql
    container_name: spain-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: spaindb
      MYSQL_USER: diego
      MYSQL_PASSWORD: diego
    ports:
      - "3306:3306"