name: Detect Production Change

on:
  push:
    branches:
      - main

jobs:
  create-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Create trigger file
        run: echo "ready-for-prod=true" > trigger.txt

      - name: Upload trigger artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-trigger
          path: trigger.txt
