name: Promote ACC to PROD

on:
  workflow_dispatch:

jobs:
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.found }}

    steps:
      - name: Try to download trigger artifact
        id: check
        uses: actions/download-artifact@v4
        with:
          name: prod-trigger
        continue-on-error: true

      - name: Validate trigger
        run: |
          if [ -f "trigger.txt" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "‚ùå No trigger found. Nothing to deploy."
          fi

  promote-to-prod:
    needs: check-trigger
    if: needs.check-trigger.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment: production

    env:
      IMAGE_NAME: lainezzz/spainapi

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull acc image
        run: docker pull $IMAGE_NAME:acc

      - name: Tag acc as prod and push
        run: |
          docker tag  $IMAGE_NAME:acc $IMAGE_NAME:prod
          docker push $IMAGE_NAME:prod

      - name: Delete trigger artifact
        run: rm trigger.txt

      - name: Cleanup action artifacts
        uses: geekyeggo/delete-artifact@v3
        with:
          name: prod-trigger
