name: Promote ACC to PROD

on:
  workflow_dispatch:

jobs:
  promote-to-prod:
    # Solo ejecuta el job si el workflow se lanza desde la rama 'main'
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    environment: production

    env:
      IMAGE_NAME: lainezzz/spainapi

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull acc image
        run: docker pull $IMAGE_NAME:acc

      - name: Tag acc as prod and push
        run: |
          docker tag  $IMAGE_NAME:acc $IMAGE_NAME:prod
          docker push $IMAGE_NAME:prod
